apps/studio/upload/urls.py
from django.urls import path
from apps.studio.upload import views


urlpatterns = [
    path('', views.StudioUploadView.as_view(), name='upload'),
    path('<draft_id>/topics/', views.StudioDraftTopicsSearchView.as_view(), name='draft-topics'),
    path('<draft_id>/', views.StudioDraftUpdateView.as_view(), name='update'),
    path('<draft_id>/generate-thumbnails/', views.GenerateVideosThumbnailsView.as_view(), name='generate-thumbnails'),
    path('<draft_id>/publish', views.StudioPublishingView.as_view(), name='publish')
]

youtube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.core.consumers import AssetController
from apps.studio.consumers import StudioConsumer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('api/', include('sage_stream.api.urls')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path("", include('apps.channel.urls', namespace='channel')),
    path('', include('apps.core.urls', namespace='assets')),
    path("channel/", include('apps.studio.urls', namespace='studio')),
    path("__debug__/", include("debug_toolbar.urls"))
]

websocket_urlpatterns = [
    path('ws/youtube/', AssetController.as_asgi()),
    path('ws/studio/<group_name>/', StudioConsumer.as_asgi()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/studio/publishing/topics/form.html
<turbo-frame id="{{ request.turbo.frame }}">
    <header class="flex items-center justify-between px-4 py-2">
        <h2>Select topics</h2>
        <button type="button" class="flex items-center justify-center p-2 hover:bg-gray-100 hover:rounded-full" data-action="click->modal#close:prevent">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 72 72"><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="m17.5 17.5l37 37m0-37l-37 37"/></svg>
        </button>
    </header>
    <div>
        <form method="get" action="{% url 'studio:draft-topics' request.user.channel.uid draft.id %}" class="px-4 py-4"
              data-controller="autosearch"
              data-action="turbo:before-fetch-request->autosearch#fetchRequest">
            <label for="id_search" class="flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m21 21l-4.343-4.343m0 0A8 8 0 1 0 5.343 5.343a8 8 0 0 0 11.314 11.314Z"/></svg>
                <input data-autosearch-target="input" type="text" name="search" {% if query %}value="{{ query }}" {% endif %} id="id_search" class="border-none py-0 px-0 w-full" placeholder="Search anything you want here."/>
            </label>
        </form>
        <form method="post" class="yt--trailer--form px-4 py-2 flex flex-col gap-4" action="{% url 'studio:update' request.user.channel.uid draft.id %}">
            {% csrf_token %}
            <div class="flex items-center flex-wrap gap-2" id="yt--topics--selected">
                {% for topic in form.instance.topics.all %}
                    {% include "pages/studio/details/topics/selected.html" %}
                {% endfor %}
            </div>
            <div class="border-t py-4">
                <div id="topics-list-with-pagination" class="flex items-center flex-wrap gap-2">Please type your topic.</div>
            </div>
        </form>
    </div>
</turbo-frame>

templates/pages/studio/publishing/topics/item.html
<div class="cursor-pointer bg-gray-100 px-3 py-2 text-sm hover:bg-blue-500 hover:text-white transition-all rounded"
     data-action="click->studio#setTopicItem click->studio#setTopicToList"
     id="yt--topic--{{ topic.id }}"
     data-uid="{{ obj.uid }}"
     data-id="{{ topic.id }}"
     data-model="{{ obj.get_model_name }}"
>
    {{ topic.name }}
</div>

templates/pages/studio/publishing/topics/list.html
{% for topic in topics %}
    {% include "pages/studio/details/topics/item.html" %}
{% empty %}
    <div>No Topics found for "{{ query }}".</div>
{% endfor %}

templates/pages/studio/publishing/topics/selected.html
<div id="yt--topic--{{ topic.id }}--item"
     class="flex items-center gap-1 border text-sm"
>
    <span class="pl-2.5">{{ topic.name }}</span>
    <button type="button" data-action="click->studio#removeTopicItem" class="px-2 py-2 hover:bg-gray-100 rounded-full"
            data-uid="{{ obj.uid }}"
            data-id="{{ topic.id }}"
            data-model="{{ obj.get_model_name }}"
    >
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 72 72"><path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="m17.5 17.5l37 37m0-37l-37 37"/></svg>
    </button>
</div>