apps/studio/customization/urls.py
from django.urls import path

from apps.studio.customization import views

urlpatterns = [
    path('', views.StudioCustomizationView.as_view(), name='customization'),
    path('branding/', views.LoadCustomizationBrandingView.as_view(), name='customization-branding'),
    path('branding/picture/', views.StudioCustomizationBrandingPictureView.as_view(), name='customization-branding-picture'),
    path('branding/banner/', views.StudioCustomizationBrandingBannerView.as_view(), name='customization-branding-banner'),

    path('layout/', views.LoadCustomizationLayoutView.as_view(), name='customization-layout'),
    path('layout/trailer/', views.LoadCustomizationLayoutTrailerView.as_view(), name='customization-layout-trailer'),
    path('layout/trailer/play/<trailer_uid>/', views.LoadCustomizationLayoutTrailerPlayView.as_view(), name='customization-layout-trailer-play'),
    path('basic-info/', views.LoadCustomizationBasicInfoView.as_view(), name='customization-basic-info'),

    path('update/channel-link-order/', views.ChannelLinkOrderView.as_view(), name='update-link-order')
]

youtube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.core.consumers import AssetController
from apps.studio.consumers import StudioConsumer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('api/', include('sage_stream.api.urls')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path("", include('apps.channel.urls', namespace='channel')),
    path('', include('apps.core.urls', namespace='assets')),
    path("channel/", include('apps.studio.urls', namespace='studio')),
    path("__debug__/", include("debug_toolbar.urls"))
]

websocket_urlpatterns = [
    path('ws/youtube/', AssetController.as_asgi()),
    path('ws/studio/<group_name>/', StudioConsumer.as_asgi()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/studio/customization/forms.py
from django import forms
from apps.channel.models import Channel, ChannelPicture, ChannelBanner


class ChannelBasicInfoForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter a channel name', 'class': 'border border-gray-400 rounded',}))
    pseudo = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter a channel handle', 'class': 'border border-gray-400 rounded',}))
    description = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'border border-gray-400 rounded',
        'placeholder': 'Enter a channel description', 'data-controller': 'textarea-autogrow', 'rows': '4',
         'data-textarea-autogrow-resize-debounce-delay-value': '500',
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Channel
        fields = ['name', 'pseudo', 'description']


class ChannelPictureForm(forms.ModelForm):
    class Meta:
        model = ChannelPicture
        fields = ['original', 'cropX', 'cropY', 'cropWidth', 'cropHeight', 'type']


class ChannelBannerForm(forms.ModelForm):
    class Meta:
        model = ChannelBanner
        fields = ['original', 'cropX', 'cropY', 'cropWidth', 'cropHeight', 'type']

apps/studio/customization/views.py
import os, cv2

from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic import TemplateView, FormView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, HttpResponse
from django.core.files.base import File
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from turbo_response import TurboStreamResponse, TurboStream

from apps.channel.models import Channel, ChannelPicture, ChannelBanner, Video, ChannelLayout, ChannelLink
from apps.studio.customization.forms import ChannelBasicInfoForm, ChannelPictureForm, ChannelBannerForm

from braces.views import CsrfExemptMixin, JSONRequestResponseMixin


class StudioCustomizationBrandingPictureView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/studio/customization/branding/picture.html'
    channel = None
    picture = None

    def dispatch(self, request, *args, **kwargs):
        self.channel = get_object_or_404(Channel, uid=kwargs['channel_uid'])
        self.picture = get_object_or_404(ChannelPicture, channel=self.channel)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return self.render_to_response({
            'form': ChannelPictureForm(instance=self.picture),
            'picture': self.picture
        })

    def post(self, request, *args, **kwargs):
        form = ChannelPictureForm(instance=self.picture, data=request.POST, files=request.FILES)
        uploaded_picture = request.FILES.get('original')
        cropX = int(float(request.POST.get('cropX')))
        cropY = int(float(request.POST.get('cropY')))
        cropWidth = int(float(request.POST.get('cropWidth')))
        cropHeight = int(float(request.POST.get('cropHeight')))

        if not os.path.exists(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}"):
            os.mkdir(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}")
        if not os.path.exists(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture"):
            os.mkdir(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture")
        if not os.path.exists(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture/temp"):
            os.mkdir(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture/temp")

        if not uploaded_picture and self.picture.original is None:
            return HttpResponseBadRequest()

        if self.picture.cropX != cropX:
            self.picture.cropX = cropX

        if self.picture.cropY != cropY:
            self.picture.cropY = cropY

        if self.picture.cropWidth != cropWidth:
            self.picture.cropWidth = cropWidth

        if self.picture.cropHeight != cropHeight:
            self.picture.cropHeight = cropHeight

        if self.picture.cropX != cropX or self.picture.cropY != cropY or self.picture.cropWidth != cropWidth or self.picture.cropHeight != cropHeight:
            self.picture.save()

        if uploaded_picture:
            picture_type = request.POST.get('type')
            picture_extension = picture_type.split('/')[-1]

            if self.picture.type != picture_type:
                self.picture.type = picture_type
                self.picture.save()

            self.picture.original.delete()
            self.picture.original.save(f"channel_picture.{picture_extension}", uploaded_picture)
        else:
            picture_extension = self.picture.type.split('/')[-1]

        original_url = f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture/temp/channel_picture.{picture_extension}"
        cropped_url = f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture/channel_thumbnail.{picture_extension}"

        image = cv2.imread(original_url)
        cropped_img = image[cropY:cropY + cropHeight, cropX:cropX + cropWidth]
        cv2.imwrite(cropped_url, cropped_img)

        self.picture.cropped.delete()
        self.picture.cropped.save(f"channel_thumbnail.{picture_extension}", File(open(cropped_url, 'rb')), save=False)
        self.picture.save()

        redirect_to = reverse('studio:customization', args=[self.channel.uid]) + '?section=branding'
        return HttpResponse(redirect_to)


class StudioCustomizationBrandingBannerView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/studio/customization/branding/banner.html'
    channel = None
    banner = None

    def dispatch(self, request, *args, **kwargs):
        self.channel = get_object_or_404(Channel, uid=kwargs['channel_uid'])
        self.banner = get_object_or_404(ChannelBanner, channel=self.channel)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return self.render_to_response({
            'form': ChannelBannerForm(instance=self.banner),
            'banner': self.banner
        })

    def post(self, request, *args, **kwargs):
        uploaded_picture = request.FILES.get('original')
        cropX = int(float(request.POST.get('cropX')))
        cropY = int(float(request.POST.get('cropY')))
        cropWidth = int(float(request.POST.get('cropWidth')))
        cropHeight = int(float(request.POST.get('cropHeight')))

        if not os.path.exists(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}"):
            os.mkdir(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}")
        if not os.path.exists(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture"):
            os.mkdir(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture")
        if not os.path.exists(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/banner"):
            os.mkdir(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/banner")
        if not os.path.exists(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture/temp"):
            os.mkdir(f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/picture/temp")

        if not uploaded_picture and self.banner.original is None:
            return HttpResponseBadRequest()

        if self.banner.cropX != cropX:
            self.banner.cropX = cropX

        if self.banner.cropY != cropY:
            self.banner.cropY = cropY

        if self.banner.cropWidth != cropWidth:
            self.banner.cropWidth = cropWidth

        if self.banner.cropHeight != cropHeight:
            self.banner.cropHeight = cropHeight

        if self.banner.cropX != cropX or self.banner.cropY != cropY or self.banner.cropWidth != cropWidth or self.banner.cropHeight != cropHeight:
            self.banner.save()

        if uploaded_picture:
            picture_type = request.POST.get('type')
            picture_extension = picture_type.split('/')[-1]

            if self.banner.type != picture_type:
                self.banner.type = picture_type
                self.banner.save()

            self.banner.original.delete()
            self.banner.original.save(f"channel_banner.{picture_extension}", uploaded_picture)
        else:
            picture_extension = self.banner.type.split('/')[-1]

        original_url = f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/banner/temp/channel_banner.{picture_extension}"
        cropped_url = f"{settings.MEDIA_ROOT}/channels/{request.user.channel.uid}/banner/channel_banner.{picture_extension}"

        image = cv2.imread(original_url)
        cropped_img = image[cropY:cropY + cropHeight, cropX:cropX + cropWidth]
        cv2.imwrite(cropped_url, cropped_img)

        self.banner.cropped.delete()
        self.banner.cropped.save(f"channel_banner.{picture_extension}", File(open(cropped_url, 'rb')), save=False)
        self.banner.save()

        redirect_to = reverse('studio:customization', args=[self.channel.uid]) + '?section=branding'
        return HttpResponse(redirect_to)


class StudioCustomizationView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/studio/customization/index.html'

    def get(self, request, *args, **kwargs):
        return self.render_to_response({
            'page': 'customization'
        })


class LoadCustomizationBasicInfoView(LoginRequiredMixin, FormView):
    template_name = 'components/pages/studio/customization/_basic_info.html'
    form_class = ChannelBasicInfoForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'instance': self.request.user.channel,
        })
        return kwargs

    def form_valid(self, form):
        form.save()
        return redirect(self.request.user.channel.get_customization_url())


class LoadCustomizationBrandingView(LoginRequiredMixin, TemplateView):
    template_name = 'components/pages/studio/customization/_branding.html'


class LoadCustomizationLayoutView(LoginRequiredMixin, TemplateView):
    template_name = 'components/pages/studio/customization/_layout.html'


class LoadCustomizationLayoutTrailerView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/studio/customization/layout/trailer.html'

    def get(self, request, *args, **kwargs):
        channel = request.user.channel
        videos = Video.objects.filter(author__channel=channel)
        paginator = Paginator(videos, 4)
        page = request.GET.get('page')
        query = None

        if 'search' in request.GET:
            query = request.GET.get('search')

            if query.strip() == '':
                results = videos
            else:
                results = videos.filter(title__icontains=query)
            paginator = Paginator(results, 4)

        try:
            page_obj = paginator.get_page(page)
        except PageNotAnInteger:
            page_obj = paginator.get_page(1)
        except EmptyPage:
            page_obj = paginator.get_page(paginator.num_pages)

        context = {
            'videos': page_obj.object_list.all(),
            'query': query,

templates/pages/studio/customization/branding/banner.html
{% extends "layout/studio.html" %}

{% block content %}
    {% if request.turbo.frame %}
        <turbo-frame id="{{ request.turbo.frame }}">
            {% with request.user.channel as channel %}
                <div>
                    <div class="flex items-center justify-between py-4 px-4">
                        <div class="text-xl font-semibold">Channel Banner Image</div>
                        <button type="button" class="flex items-center justify-center" data-action="click->modal#close:prevent">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 32 32"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2 30L30 2m0 28L2 2"/></svg>
                        </button>
                    </div>
                    <div>
                        <form method="post"
                              action="{% url 'studio:customization-branding-banner' channel.uid %}"
                              data-controller="dragdrop"
                              data-dragdrop-ratio-value="rectangle"
                              data-dragdrop-url-value="{% url 'studio:customization-branding-banner' channel.uid %}"
                              enctype="multipart/form-data"
                              data-action="submit->dragdrop#sendRequest"
                              data-crop-x="{{ picture.cropX }}"
                              data-crop-y="{{ picture.cropY }}"
                              data-crop-width="{{ picture.cropWidth }}"
                              data-crop-height="{{ picture.cropHeight }}"
                        >
                            {% csrf_token %}

                            <div class="preview" data-dragdrop-target="preview">
                                <img src="{{ channel.banner.original.url }}" alt="" class="preview-img aspect-video" />
                            </div>
                            <div class="flex items-center gap-4 px-4 py-4">
                                <label for="{{ form.original.id_for_label }}" class="cursor-pointer text-blue-500 font-semibold text-sm">
                                    Change
                                    <input type="file" hidden name="original" value="{{ form.instance.original }}" accept="image/*" id="{{ form.original.id_for_label }}" data-action="input->dragdrop#changeImage" />
                                </label>
                                <button type="submit">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            {% endwith %}
        </turbo-frame>
    {% endif %}
{% endblock %}

templates/pages/studio/customization/branding/picture.html
{% extends "layout/studio.html" %}

{% block content %}
    {% if request.turbo.frame %}
        <turbo-frame id="{{ request.turbo.frame }}">
            {% with request.user.channel as channel %}
                <div>
                    <div class="flex items-center justify-between py-4 px-4">
                        <div class="text-xl font-semibold">Channel Picture</div>
                        <button type="button" class="flex items-center justify-center" data-action="click->modal#close:prevent">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 32 32"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2 30L30 2m0 28L2 2"/></svg>
                        </button>
                    </div>
                    <div>
                        <form method="post"
                              action="{% url 'studio:customization-branding-picture' channel.uid %}"
                              data-controller="dragdrop"
                              data-dragdrop-url-value="{% url 'studio:customization-branding-picture' channel.uid %}"
                              enctype="multipart/form-data"
                              data-action="submit->dragdrop#sendRequest"
                              data-crop-x="{{ picture.cropX }}"
                              data-crop-y="{{ picture.cropY }}"
                              data-crop-width="{{ picture.cropWidth }}"
                              data-crop-height="{{ picture.cropHeight }}"
                        >
                            {% csrf_token %}

                            <div class="preview" data-dragdrop-target="preview">
                                <img src="{{ channel.picture.original.url }}" alt="" class="preview-img aspect-video object-contain" />
                            </div>
                            <div class="flex items-center gap-4 px-4 py-4">
                                <label for="{{ form.original.id_for_label }}" class="cursor-pointer text-blue-500 font-semibold text-sm">
                                    Change
                                    <input type="file" hidden name="original" value="{{ form.instance.original }}" accept="image/*" id="{{ form.original.id_for_label }}" data-action="input->dragdrop#changeImage" />
                                </label>
                                <button type="submit">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            {% endwith %}
        </turbo-frame>
    {% endif %}
{% endblock %}